# -*- coding: utf-8 -*-
"""confusion_matrix_and_Quest_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16XGjOZHyOfKtVITlf3Dx13Rv3eo9Z8jc
"""

!pip install wandb

import wandb
wandb.login(key='da5365b4335ad8c7a1df7f3653ec9d0b092e8b09')

from tensorflow.keras.datasets import fashion_mnist

# Load Fashion MNIST dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# Preprocess the data (flatten and normalize)
x_train = x_train.reshape((x_train.shape[0], -1)).astype('float32') / 255.0
x_test = x_test.reshape((x_test.shape[0], -1)).astype('float32') / 255.0



from tensorflow.keras.utils import to_categorical

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

import feed_forward_neural_network as FFNN

# Initialize FFNN
import numpy as np
# Initialize FFNN
Neural_Net = FFNN.feed_forward_neural_network(layer_sizes=[x_train.shape[1],128,128,128,128,128, 10],L = 5, epochs=10, l_rate=0.001, batch_size=32, activation_func='tanh', loss_func='cross_entropy', output_activ_func='softmax', initializer='random')
wandb.init(project='DL_Ass_1')
# Train the model
Neural_Net.nesterov_accelerated_gradient_descent(x_train, y_train_onehot, x_test, y_test_onehot)

test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
print("Test Accuracy: " ,' ',test_acc)
print("Test Loss: " ,' ',test_loss)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay



unique_labels = np.unique(y_test)
label_names = [str(label) for label in unique_labels]


test_acc, test_loss, _, y_pred = Neural_Net.model_performance(x_test, y_test_onehot)

y_true = [i for i in y_test]
cm = confusion_matrix(y_true, y_pred)


import matplotlib.pyplot as plt

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.gca().invert_yaxis()  # Invert the y-axis
plt.savefig('confusion_matrix.png')  # Save the plot as an image
plt.show()



# Log the confusion matrix as an image
wandb.log({"Confusion_Matrix": wandb.Image('confusion_matrix.png')})

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
number_of_classes = 10
class_mapping_dic = {0: "T-shirt", 1: "Trouser", 2: "Pullover", 3: "Dress", 4: "Coat", 5: "Sandal", 6: "Shirt", 7: "Sneaker", 8: "Bag", 9: "Ankle boot"}

# Downloading the fashion-MNIST dataset
(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()
number_of_classes = 10
class_mapping_dic = {0: "T-shirt", 1: "Trouser", 2: "Pullover", 3: "Dress", 4: "Coat", 5: "Sandal", 6: "Shirt", 7: "Sneaker", 8: "Bag", 9: "Ankle boot"}

# ploting 1 sample image for each class
plt.figure(figsize=[12, 5])
image_list_wb = []
class_list_wb = []

for i in range(number_of_classes):
    position_of_image = np.argmax(train_labels==i)
    image = train_images[position_of_image,:,:]
    plt.subplot(2, 5, i+1)
    plt.imshow(image)
    plt.title(class_mapping_dic[i])
    image_list_wb.append(image)
    class_list_wb.append(class_mapping_dic[i])

#loging image as media to wandb
wandb.log({"Question 1": [wandb.Image(img, caption=caption) for img, caption in zip(image_list_wb, class_list_wb)]})

wandb.finish()