# -*- coding: utf-8 -*-
"""train_for_mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14c-KUSFTPXFWSTTHVJtsolggDhC47csR
"""

!pip install wandb

import wandb
wandb.login(key='da5365b4335ad8c7a1df7f3653ec9d0b092e8b09')

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import pdb
import math
from tqdm import tqdm

np.random.seed(1)

class FFNN():
    # Initializing the hyperparameters
    def __init__(self, layer_sizes, L, epochs, l_rate=0.001, batch_size=16, activation_func='sigmoid', loss_func='cross_entropy', output_activ_func='softmax', initializer='xavier'):

        self.layer_sizes = layer_sizes       # Size of each layer
        self.L = L +2               # Number of layer
        self.epochs = epochs            # Total number of epochs
        self.l_rate = l_rate            # Learning rate
        self.batch_size = batch_size        # Size of a batch
        self.activation_func = activation_func    # Activation function for the hidden layers
        self.initializer = initializer        # For initializing weights
        self.loss_func = loss_func          # Loss function
        self.output_activ_func = output_activ_func    # Activation function for the output layer
        self.parameters_w, self.parameters_b = self.initialize_model_parameters()    # Initializing the parameters -- weights and biases

        print()
        print("Hyperparameters Values ")
        print('---------------------------------------------------------')
        print("Number of Hidden Layers: " ,self.L - 2)
        print("Layer Sizes: " ,self.layer_sizes)
        print("Number of Epochs: " ,self.epochs)
        print("Learning Rate: " ,self.l_rate)
        print("Batch Size: " ,self.batch_size)
        print("Activation Function: " + self.activation_func)
        print("Loss Function: " + self.loss_func)
        print("Output Activation Function: " + self.output_activ_func)
        print("Initializer: " + self.initializer)
        print("----------------------------------------------------------")
        print()

    # Activation function for the hidden layers
    def activation(self, x, derivative=False):
        if self.activation_func == 'sigmoid':
            if derivative:
                return (np.exp(-x))/((np.exp(-x)+1)**2)
            return 1/(1 + np.exp(-x))
        elif self.activation_func == 'tanh':
            temp1 = (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
            if derivative:
                return 1 - (temp1)**2
            return temp1
        elif self.activation_func == 'relu':
            if derivative:
                return 1. * (x > 0)
            return x * (x > 0)

    # Activation function for the output layer
    def output_activation(self, x, derivative=False):
        if self.output_activ_func == 'softmax':
            exps = np.exp(x - x.max())
            if derivative:
                return exps / np.sum(exps, axis=0) * (1 - exps / np.sum(exps, axis=0))
            return exps / np.sum(exps, axis=0)

    # Initializing the parameters -- weights and biases
    def initialize_model_parameters(self):
        parameters_w = [0]
        parameters_b = [0]
        for l in range(1, self.L):
            if self.initializer == 'random':
                parameters_w.append(np.random.randn(self.layer_sizes[l], self.layer_sizes[l - 1])*0.1)
            elif self.initializer == 'xavier':
                parameters_w.append(np.random.randn(self.layer_sizes[l], self.layer_sizes[l - 1]) * np.sqrt(2/ (self.layer_sizes[l - 1] + self.layer_sizes[l])))
            parameters_b.append(np.zeros((self.layer_sizes[l], 1)))
        return parameters_w, parameters_b

    # Initialize gradients
    def initialize_gradients(self):
        gradients_w = []
        gradients_b = []
        for l in range(1, self.L):
            gradients_w.append(np.zeros((self.layer_sizes[l], self.layer_sizes[l - 1])))
            gradients_b.append(np.zeros((self.layer_sizes[l], 1)))
        return gradients_w, gradients_b

    # Forward Propagation
    def forward_propagation(self, x):
        pre_activations = [0]
        activations = []

        activations.append(x.reshape(len(x), 1))

        # From layer 1 to L-1
        for i in range(1, self.L-1):
            pre_activations.append(self.parameters_b[i] + np.matmul(self.parameters_w[i], activations[i-1]))
            activations.append(self.activation(pre_activations[i], derivative=False))

        # Last layer L
        pre_activations.append(self.parameters_b[self.L-1] + np.matmul(self.parameters_w[self.L-1], activations[self.L-2]))
        activations.append(self.output_activation(pre_activations[self.L-1]))

        return activations, pre_activations

    # Back Propagation
    def backward_propagation(self, y, activations, pre_activations):
        gradients_w, gradients_b = self.initialize_gradients()
        gradients_a = [None] * self.L
        gradients_h = [None] * self.L

        # Compute output gradient
        f_x = activations[self.L-1]
        e_y = y.reshape(len(y), 1)

        # Gradient with respect to last layer
        if self.loss_func == 'cross_entropy':
            gradients_a[self.L-1] = (f_x - e_y)
        elif self.loss_func == 'squared_error':
            gradients_a[self.L-1] = (f_x - e_y)*f_x*(1-f_x)

        # Compute gradients for hidden layers
        for k in range(self.L-1, 0, -1):
            gradients_w[k-1] = np.outer(gradients_a[k], activations[k-1])
            gradients_b[k-1] = gradients_a[k]
            gradients_h[k-1] = np.dot(self.parameters_w[k].T, gradients_a[k])
            if k > 1:
                gradients_a[k-1] = gradients_h[k-1] * self.activation(pre_activations[k-1], derivative=True)

        return gradients_w, gradients_b, gradients_a, gradients_h

    # Compute Loss
    def compute_loss(self, yHat, y):
        if self.loss_func == 'cross_entropy':
            indexClass = np.argmax(y)
            prob = yHat[indexClass]
            if(prob<=0):
                prob = prob + 0.0000000001
            loss = -np.log(prob)
            return loss
        if self.loss_func == 'squared_error':
            loss = 0.5*np.sum((y-yHat)**2)
            return loss

    # Find the accuracy
    def model_performance(self, x_test, y_test):
        predictions = []
        y_true = []
        y_pred = []
        loss = []
        for x, y in zip(x_test ,y_test):
            activations, pre_activations = self.forward_propagation(x)
            predicted_class = np.argmax(activations[self.L-1])
            y = y.reshape(len(y), 1)
            actual_class = np.argmax(y)
            y_true.append(actual_class)
            y_pred.append(predicted_class)
            predictions.append(predicted_class == actual_class)
            loss.append(self.compute_loss(activations[self.L-1], y))

        accuracy = (np.sum(predictions)*100)/len(predictions)
        tot_loss = np.sum(loss)/len(loss)

        return accuracy, tot_loss, y_true, y_pred

    # Optimization Algorithm: Stochastic Gradient Descent
    def stochastic_gradient_descent(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate

        for epoch in range(self.epochs):
            print(" =============== Epoch Number: " + str(epoch+1) + " =============== ")

            # Initialize the gradients
            gradients_w, gradients_b = self.initialize_gradients()

            # Learn the parameters
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):

                # Forward Propagation
                activations, pre_activations = self.forward_propagation(x)

                # Backward Propagation
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)

                # Update parameters
                for i in range(1,self.L):
                    self.parameters_w[i] = self.parameters_w[i] - eta * current_gradients_w[i-1]
                    self.parameters_b[i] = self.parameters_b[i] - eta * current_gradients_b[i-1]

            # Validation Accuracy
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})


    def momentum_gradient_descent(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta = 0.9  # Momentum hyperparameter
        v_w, v_b = self.initialize_gradients()  # Initialize velocity
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    v_w[i-1] = beta * v_w[i-1] + (1 - beta) * current_gradients_w[i-1]
                    v_b[i-1] = beta * v_b[i-1] + (1 - beta) * current_gradients_b[i-1]
                    self.parameters_w[i] -= eta * v_w[i-1]
                    self.parameters_b[i] -= eta * v_b[i-1]
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})


    def nesterov_accelerated_gradient_descent(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta = 0.9  # Momentum hyperparameter
        v_w, v_b = self.initialize_gradients()  # Initialize velocity
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    v_w[i-1] = beta * v_w[i-1] + (1 - beta) * current_gradients_w[i-1]
                    v_b[i-1] = beta * v_b[i-1] + (1 - beta) * current_gradients_b[i-1]
                    self.parameters_w[i] -= eta * v_w[i-1]
                    self.parameters_b[i] -= eta * v_b[i-1]

            # Validation Accuracy
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})


    def rmsprop(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta = 0.9  # RMSprop decay factor
        epsilon = 1e-8
        v_w, v_b = self.initialize_gradients()  # Initialize moving average of squared gradients
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    v_w[i-1] = beta * v_w[i-1] + (1 - beta) * np.square(current_gradients_w[i-1])
                    v_b[i-1] = beta * v_b[i-1] + (1 - beta) * np.square(current_gradients_b[i-1])
                    self.parameters_w[i] -= (eta / np.sqrt(v_w[i-1] + epsilon)) * current_gradients_w[i-1]
                    self.parameters_b[i] -= (eta / np.sqrt(v_b[i-1] + epsilon)) * current_gradients_b[i-1]
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})



    def adam(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta1 = 0.9  # Exponential decay rates for moment estimates
        beta2 = 0.999
        epsilon = 1e-8
        m_w, m_b = self.initialize_gradients()  # Initialize 1st moment vector
        v_w, v_b = self.initialize_gradients()  # Initialize 2nd moment vector
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    m_w[i-1] = beta1 * m_w[i-1] + (1 - beta1) * current_gradients_w[i-1]
                    m_b[i-1] = beta1 * m_b[i-1] + (1 - beta1) * current_gradients_b[i-1]
                    v_w[i-1] = beta2 * v_w[i-1] + (1 - beta2) * np.square(current_gradients_w[i-1])
                    v_b[i-1] = beta2 * v_b[i-1] + (1 - beta2) * np.square(current_gradients_b[i-1])
                    m_w_hat = m_w[i-1] / (1 - beta1 ** (epoch + 1))
                    m_b_hat = m_b[i-1] / (1 - beta1 ** (epoch + 1))
                    v_w_hat = v_w[i-1] / (1 - beta2 ** (epoch + 1))
                    v_b_hat = v_b[i-1] / (1 - beta2 ** (epoch + 1))
                    self.parameters_w[i] -= (eta / (np.sqrt(v_w_hat) + epsilon)) * m_w_hat
                    self.parameters_b[i] -= (eta / (np.sqrt(v_b_hat) + epsilon)) * m_b_hat
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})



    def nadam(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta1 = 0.9  # Exponential decay rates for moment estimates
        beta2 = 0.999
        epsilon = 1e-8
        m_w, m_b = self.initialize_gradients()  # Initialize 1st moment vector
        v_w, v_b = self.initialize_gradients()  # Initialize 2nd moment vector
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    m_w[i-1] = beta1 * m_w[i-1] + (1 - beta1) * current_gradients_w[i-1]
                    m_b[i-1] = beta1 * m_b[i-1] + (1 - beta1) * current_gradients_b[i-1]
                    v_w[i-1] = beta2 * v_w[i-1] + (1 - beta2) * np.square(current_gradients_w[i-1])
                    v_b[i-1] = beta2 * v_b[i-1] + (1 - beta2) * np.square(current_gradients_b[i-1])
                    m_w_hat = m_w[i-1] / (1 - beta1 ** (epoch + 1))
                    m_b_hat = m_b[i-1] / (1 - beta1 ** (epoch + 1))
                    v_w_hat = v_w[i-1] / (1 - beta2 ** (epoch + 1))
                    v_b_hat = v_b[i-1] / (1 - beta2 ** (epoch + 1))
                    self.parameters_w[i] -= (eta / (np.sqrt(v_w_hat) + epsilon)) * (beta1 * m_w_hat + (1 - beta1) * current_gradients_w[i-1])
                    self.parameters_b[i] -= (eta / (np.sqrt(v_b_hat) + epsilon)) * (beta1 * m_b_hat + (1 - beta1) * current_gradients_b[i-1])
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})

from tensorflow.keras.datasets import mnist

# Load Fashion MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Preprocess the data (flatten and normalize)
x_train = x_train.reshape((x_train.shape[0], -1)).astype('float32') / 255.0
x_test = x_test.reshape((x_test.shape[0], -1)).astype('float32') / 255.0



from tensorflow.keras.utils import to_categorical

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

# Initialize FFNN
import numpy as np
# Initialize FFNN
Neural_Net = FFNN(layer_sizes=[x_train.shape[1],128,128,128,128,128, 10],L = 5, epochs=10, l_rate=0.001, batch_size=32, activation_func='tanh', loss_func='cross_entropy', output_activ_func='softmax', initializer='random')
wandb.init(project='DL_Ass_1_Try_14')
# Train the model
Neural_Net.stochastic_gradient_descent(x_train, y_train_onehot, x_test, y_test_onehot)

test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
print("Test Accuracy: " ,' ',test_acc)
print("Test Loss: " ,' ',test_loss)

# Initialize FFNN
import numpy as np
# Initialize FFNN
Neural_Net = FFNN(layer_sizes=[x_train.shape[1],128,128,128, 10],L = 3, epochs=10, l_rate=0.001, batch_size=64, activation_func='tanh', loss_func='cross_entropy', output_activ_func='softmax', initializer='random')

# Train the model
Neural_Net.nadam(x_train, y_train_onehot, x_test, y_test_onehot)

test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
print("Test Accuracy: " ,' ',test_acc)
print("Test Loss: " ,' ',test_loss)

# Initialize FFNN
import numpy as np
# Initialize FFNN
Neural_Net = FFNN(layer_sizes=[x_train.shape[1],128,128,128, 10],L = 3, epochs=10, l_rate=0.0001, batch_size=16, activation_func='relu', loss_func='cross_entropy', output_activ_func='softmax', initializer='random')

# Train the model
Neural_Net.nadam(x_train, y_train_onehot, x_test, y_test_onehot)

test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
print("Test Accuracy: " ,' ',test_acc)
print("Test Loss: " ,' ',test_loss)

# Initialize FFNN
import numpy as np
# Initialize FFNN
Neural_Net = FFNN(layer_sizes=[x_train.shape[1],128,128,128, 10],L = 3, epochs=10, l_rate=0.0001, batch_size=16, activation_func='relu', loss_func='cross_entropy', output_activ_func='softmax', initializer='random')

# Train the model
Neural_Net.adam(x_train, y_train_onehot, x_test, y_test_onehot)

test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
print("Test Accuracy: " ,' ',test_acc)
print("Test Loss: " ,' ',test_loss)

wandb.finish()



"""Learning Rate of 0.001 seems to be the standard default and works well in most cases.
More epochs are better unless there is overfitting, which doesn't seem to be occurring. Hence we set epochs to 10 and L2 weight decay to 0. This also means the larger layer the better, so we set layer size to 128.
Xavier weight initialization, ReLU activation and Adam optimizer are individually known to work better in practice over their respective alternatives, which has been demonstrated in research.
Batch size doesn't generally impact performance much but more impacts the speed. So we set batch size to 64

Both the datasets are related to a 10 class classification problem.

The image sizes are also the same in both datasets.

Hence, the overall objective functions would be similar in both datasets. So the features to be learnt/discriminated by each neuron, the optimization techniques and the hyperparameter configurations that perform well in the Fashion-MNIST dataset are expected to produce good results with the MNIST dataset as well. Therefore we select the top 3 configurations (with minor changes based on the observations from the various plots deduced from the sweep, if needed) with respect to the validation accuracy in the Fashion-MNIST dataset as recommendations for the MNIST Dataset.

{\small Xavier initialization}Xavier initialization, L2 regularization\textbf{\small L2 regularization}L2 regularization, and data-augmentation\textbf{\small data-augmentation}data-augmentation may give an accuracy close to 95%.

The number of hidden layers equal to 4 gives optimum performance and seldom leads to local optima compared to 3 and 5 layers.

We observe that sigmoid generally perform very poorly compared to tanh and relu functions. This may be due to the sigmoid's gradient being very less at higher values of x and hence the number of epochs may be very small to give good results. Relu function is more sensitive to other parameters and is able to achieve both very low values and very high values of accuracy.

SGD generally gives a medium or good accuracy and very rarely gives bad values. The medium accuracy values given by SGD might be due to 10 epochs not being sufficient for this optimizer.

SGD, Adam, Nadam, Momentum, and Nesterov fight for the topmost spots and perform roughly equally in this dataset.

To get an accuracy close to 95 percent, one would likely have to make a much more complex network and add more regularization to it.
"""