# -*- coding: utf-8 -*-
"""train_for_squared error.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jL_nSWwghlBEOAQIBrymzWCiJpqjkzFR
"""

!pip install wandb

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np
import pdb
import math
from tqdm import tqdm

np.random.seed(1)

class FFNN():
    # Initializing the hyperparameters
    def __init__(self, layer_sizes, L, epochs, l_rate=0.001, batch_size=16, activation_func='sigmoid', loss_func='cross_entropy', output_activ_func='softmax', initializer='xavier'):

        self.layer_sizes = layer_sizes       # Size of each layer
        self.L = L +2               # Number of layer
        self.epochs = epochs            # Total number of epochs
        self.l_rate = l_rate            # Learning rate
        self.batch_size = batch_size        # Size of a batch
        self.activation_func = activation_func    # Activation function for the hidden layers
        self.initializer = initializer        # For initializing weights
        self.loss_func = loss_func          # Loss function
        self.output_activ_func = output_activ_func    # Activation function for the output layer
        self.parameters_w, self.parameters_b = self.initialize_model_parameters()    # Initializing the parameters -- weights and biases

        print()
        print("Hyperparameters Values ")
        print('---------------------------------------------------------')
        print("Number of Hidden Layers: " ,self.L - 2)
        print("Layer Sizes: " ,self.layer_sizes)
        print("Number of Epochs: " ,self.epochs)
        print("Learning Rate: " ,self.l_rate)
        print("Batch Size: " ,self.batch_size)
        print("Activation Function: " + self.activation_func)
        print("Loss Function: " + self.loss_func)
        print("Output Activation Function: " + self.output_activ_func)
        print("Initializer: " + self.initializer)
        print("----------------------------------------------------------")
        print()

    # Activation function for the hidden layers
    def activation(self, x, derivative=False):
        if self.activation_func == 'sigmoid':
            if derivative:
                return (np.exp(-x))/((np.exp(-x)+1)**2)
            return 1/(1 + np.exp(-x))
        elif self.activation_func == 'tanh':
            temp1 = (np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))
            if derivative:
                return 1 - (temp1)**2
            return temp1
        elif self.activation_func == 'relu':
            if derivative:
                return 1. * (x > 0)
            return x * (x > 0)

    # Activation function for the output layer
    def output_activation(self, x, derivative=False):
        if self.output_activ_func == 'softmax':
            exps = np.exp(x - x.max())
            if derivative:
                return exps / np.sum(exps, axis=0) * (1 - exps / np.sum(exps, axis=0))
            return exps / np.sum(exps, axis=0)

    # Initializing the parameters -- weights and biases
    def initialize_model_parameters(self):
        parameters_w = [0]
        parameters_b = [0]
        for l in range(1, self.L):
            if self.initializer == 'random':
                parameters_w.append(np.random.randn(self.layer_sizes[l], self.layer_sizes[l - 1])*0.1)
            elif self.initializer == 'xavier':
                parameters_w.append(np.random.randn(self.layer_sizes[l], self.layer_sizes[l - 1]) * np.sqrt(2/ (self.layer_sizes[l - 1] + self.layer_sizes[l])))
            parameters_b.append(np.zeros((self.layer_sizes[l], 1)))
        return parameters_w, parameters_b

    # Initialize gradients
    def initialize_gradients(self):
        gradients_w = []
        gradients_b = []
        for l in range(1, self.L):
            gradients_w.append(np.zeros((self.layer_sizes[l], self.layer_sizes[l - 1])))
            gradients_b.append(np.zeros((self.layer_sizes[l], 1)))
        return gradients_w, gradients_b

    # Forward Propagation
    def forward_propagation(self, x):
        pre_activations = [0]
        activations = []

        activations.append(x.reshape(len(x), 1))

        # From layer 1 to L-1
        for i in range(1, self.L-1):
            pre_activations.append(self.parameters_b[i] + np.matmul(self.parameters_w[i], activations[i-1]))
            activations.append(self.activation(pre_activations[i], derivative=False))

        # Last layer L
        pre_activations.append(self.parameters_b[self.L-1] + np.matmul(self.parameters_w[self.L-1], activations[self.L-2]))
        activations.append(self.output_activation(pre_activations[self.L-1]))

        return activations, pre_activations

    # Back Propagation
    def backward_propagation(self, y, activations, pre_activations):
        gradients_w, gradients_b = self.initialize_gradients()
        gradients_a = [None] * self.L
        gradients_h = [None] * self.L

        # Compute output gradient
        f_x = activations[self.L-1]
        e_y = y.reshape(len(y), 1)

        # Gradient with respect to last layer
        if self.loss_func == 'cross_entropy':
            gradients_a[self.L-1] = (f_x - e_y)
        elif self.loss_func == 'squared_error':
            gradients_a[self.L-1] = (f_x - e_y)*f_x*(1-f_x)

        # Compute gradients for hidden layers
        for k in range(self.L-1, 0, -1):
            gradients_w[k-1] = np.outer(gradients_a[k], activations[k-1])
            gradients_b[k-1] = gradients_a[k]
            gradients_h[k-1] = np.dot(self.parameters_w[k].T, gradients_a[k])
            if k > 1:
                gradients_a[k-1] = gradients_h[k-1] * self.activation(pre_activations[k-1], derivative=True)

        return gradients_w, gradients_b, gradients_a, gradients_h

    # Compute Loss
    def compute_loss(self, yHat, y):
        if self.loss_func == 'cross_entropy':
            indexClass = np.argmax(y)
            prob = yHat[indexClass]
            if(prob<=0):
                prob = prob + 0.0000000001
            loss = -np.log(prob)
            return loss
        if self.loss_func == 'squared_error':
            loss = 0.5*np.sum((y-yHat)**2)
            return loss

    # Find the accuracy
    def model_performance(self, x_test, y_test):
        predictions = []
        y_true = []
        y_pred = []
        loss = []
        for x, y in zip(x_test ,y_test):
            activations, pre_activations = self.forward_propagation(x)
            predicted_class = np.argmax(activations[self.L-1])
            y = y.reshape(len(y), 1)
            actual_class = np.argmax(y)
            y_true.append(actual_class)
            y_pred.append(predicted_class)
            predictions.append(predicted_class == actual_class)
            loss.append(self.compute_loss(activations[self.L-1], y))

        accuracy = (np.sum(predictions)*100)/len(predictions)
        tot_loss = np.sum(loss)/len(loss)

        return accuracy, tot_loss, y_true, y_pred

    # Optimization Algorithm: Stochastic Gradient Descent
    def stochastic_gradient_descent(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate

        for epoch in range(self.epochs):
            print(" =============== Epoch Number: " + str(epoch+1) + " =============== ")

            # Initialize the gradients
            gradients_w, gradients_b = self.initialize_gradients()

            # Learn the parameters
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):

                # Forward Propagation
                activations, pre_activations = self.forward_propagation(x)

                # Backward Propagation
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)

                # Update parameters
                for i in range(1,self.L):
                    self.parameters_w[i] = self.parameters_w[i] - eta * current_gradients_w[i-1]
                    self.parameters_b[i] = self.parameters_b[i] - eta * current_gradients_b[i-1]

            # Validation Accuracy
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})


    def momentum_gradient_descent(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta = 0.9  # Momentum hyperparameter
        v_w, v_b = self.initialize_gradients()  # Initialize velocity
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    v_w[i-1] = beta * v_w[i-1] + (1 - beta) * current_gradients_w[i-1]
                    v_b[i-1] = beta * v_b[i-1] + (1 - beta) * current_gradients_b[i-1]
                    self.parameters_w[i] -= eta * v_w[i-1]
                    self.parameters_b[i] -= eta * v_b[i-1]
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})


    def nesterov_accelerated_gradient_descent(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta = 0.9  # Momentum hyperparameter
        v_w, v_b = self.initialize_gradients()  # Initialize velocity
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    v_w[i-1] = beta * v_w[i-1] + (1 - beta) * current_gradients_w[i-1]
                    v_b[i-1] = beta * v_b[i-1] + (1 - beta) * current_gradients_b[i-1]
                    self.parameters_w[i] -= eta * v_w[i-1]
                    self.parameters_b[i] -= eta * v_b[i-1]

            # Validation Accuracy
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})


    def rmsprop(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta = 0.9  # RMSprop decay factor
        epsilon = 1e-8
        v_w, v_b = self.initialize_gradients()  # Initialize moving average of squared gradients
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    v_w[i-1] = beta * v_w[i-1] + (1 - beta) * np.square(current_gradients_w[i-1])
                    v_b[i-1] = beta * v_b[i-1] + (1 - beta) * np.square(current_gradients_b[i-1])
                    self.parameters_w[i] -= (eta / np.sqrt(v_w[i-1] + epsilon)) * current_gradients_w[i-1]
                    self.parameters_b[i] -= (eta / np.sqrt(v_b[i-1] + epsilon)) * current_gradients_b[i-1]
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})



    def adam(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta1 = 0.9  # Exponential decay rates for moment estimates
        beta2 = 0.999
        epsilon = 1e-8
        m_w, m_b = self.initialize_gradients()  # Initialize 1st moment vector
        v_w, v_b = self.initialize_gradients()  # Initialize 2nd moment vector
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    m_w[i-1] = beta1 * m_w[i-1] + (1 - beta1) * current_gradients_w[i-1]
                    m_b[i-1] = beta1 * m_b[i-1] + (1 - beta1) * current_gradients_b[i-1]
                    v_w[i-1] = beta2 * v_w[i-1] + (1 - beta2) * np.square(current_gradients_w[i-1])
                    v_b[i-1] = beta2 * v_b[i-1] + (1 - beta2) * np.square(current_gradients_b[i-1])
                    m_w_hat = m_w[i-1] / (1 - beta1 ** (epoch + 1))
                    m_b_hat = m_b[i-1] / (1 - beta1 ** (epoch + 1))
                    v_w_hat = v_w[i-1] / (1 - beta2 ** (epoch + 1))
                    v_b_hat = v_b[i-1] / (1 - beta2 ** (epoch + 1))
                    self.parameters_w[i] -= (eta / (np.sqrt(v_w_hat) + epsilon)) * m_w_hat
                    self.parameters_b[i] -= (eta / (np.sqrt(v_b_hat) + epsilon)) * m_b_hat
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})



    def nadam(self, x_train, y_train, x_val, y_val):
        eta = self.l_rate
        beta1 = 0.9  # Exponential decay rates for moment estimates
        beta2 = 0.999
        epsilon = 1e-8
        m_w, m_b = self.initialize_gradients()  # Initialize 1st moment vector
        v_w, v_b = self.initialize_gradients()  # Initialize 2nd moment vector
        for epoch in range(self.epochs):
            for x, y in tqdm(zip(x_train, y_train), total=len(x_train)):
                activations, pre_activations = self.forward_propagation(x)
                current_gradients_w, current_gradients_b, _, _ = self.backward_propagation(y, activations, pre_activations)
                for i in range(1, self.L):
                    m_w[i-1] = beta1 * m_w[i-1] + (1 - beta1) * current_gradients_w[i-1]
                    m_b[i-1] = beta1 * m_b[i-1] + (1 - beta1) * current_gradients_b[i-1]
                    v_w[i-1] = beta2 * v_w[i-1] + (1 - beta2) * np.square(current_gradients_w[i-1])
                    v_b[i-1] = beta2 * v_b[i-1] + (1 - beta2) * np.square(current_gradients_b[i-1])
                    m_w_hat = m_w[i-1] / (1 - beta1 ** (epoch + 1))
                    m_b_hat = m_b[i-1] / (1 - beta1 ** (epoch + 1))
                    v_w_hat = v_w[i-1] / (1 - beta2 ** (epoch + 1))
                    v_b_hat = v_b[i-1] / (1 - beta2 ** (epoch + 1))
                    self.parameters_w[i] -= (eta / (np.sqrt(v_w_hat) + epsilon)) * (beta1 * m_w_hat + (1 - beta1) * current_gradients_w[i-1])
                    self.parameters_b[i] -= (eta / (np.sqrt(v_b_hat) + epsilon)) * (beta1 * m_b_hat + (1 - beta1) * current_gradients_b[i-1])
            train_acc, train_loss, _, _ = self.model_performance(x_train, y_train)
            val_acc, val_loss, _, _ = self.model_performance(x_val, y_val)
            print("Training Accuracy = ",train_acc)
            print("Training Loss = ",train_loss)
            print("Validation Accuracy = ",val_acc)
            print("Validation Loss = ",val_loss)
            wandb.log({"val_acc": val_acc, "train_acc": train_acc, "val_loss": val_loss, "train_loss": train_loss, "epoch": epoch+1})

import wandb
wandb.login(key='da5365b4335ad8c7a1df7f3653ec9d0b092e8b09')

from tensorflow.keras.datasets import fashion_mnist

# Load Fashion MNIST dataset
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

# Preprocess the data (flatten and normalize)
x_train = x_train.reshape((x_train.shape[0], -1)).astype('float32') / 255.0
x_test = x_test.reshape((x_test.shape[0], -1)).astype('float32') / 255.0



from tensorflow.keras.utils import to_categorical

y_train_onehot = to_categorical(y_train)
y_test_onehot = to_categorical(y_test)

# Initialize FFNN
import numpy as np
# Initialize FFNN
Neural_Net = FFNN(layer_sizes=[x_train.shape[1],128,128,128,128,128, 10],L = 5, epochs=10, l_rate=0.001, batch_size=32, activation_func='tanh', loss_func='cross_entropy', output_activ_func='softmax', initializer='random')

# Train the model
Neural_Net.nesterov_accelerated_gradient_descent(x_train, y_train_onehot, x_test, y_test_onehot)

test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
print("Test Accuracy: " ,' ',test_acc)
print("Test Loss: " ,' ',test_loss)

sweep_config = {
    'method': 'random',
    'name' : 'sweep cross entropy',
    'metric': {
        'name': 'val_accuracy',
        'goal': 'maximize'
    },
    'parameters': {
        'epochs': {
            'values': [5, 10]
        },
        'num_hidden_layers': {
            'values': [3, 4]
        },
        'hidden_layer_size': {
            'values': [32, 64]
        },
        'weight_decay': {
            'values': [0, 0.0005, 0.5]
        },
        'learning_rate': {
            'values': [1e-3, 1e-4]
        },
        'optimizer': {
            'values': ['sgd', 'mgd', 'nag', 'rmsprop', 'adam', 'nadam']
        },
        'batch_size': {
            'values': [16, 32, 64]
        },
        'weight_initialization': {
            'values': ['random', 'xavier']
        },
        'activation_function': {
            'values': ['sigmoid', 'tanh', 'relu']
        }
    }
}

sweep_id = wandb.sweep(sweep=sweep_config, project='DL_Ass_1_try_13')

def train(x_train, y_train, x_val, y_val,optimizer,Neural_Net):
    if optimizer == 'sgd':
      Neural_Net.stochastic_gradient_descent(x_train, y_train, x_val, y_val)
    elif optimizer == 'mgd':
      Neural_Net.momentum_gradient_descent(x_train, y_train, x_val, y_val)
    elif optimizer == 'nag':
      Neural_Net.nesterov_accelerated_gradient_descent(x_train, y_train, x_val, y_val)
    elif optimizer == 'rmsprop':
      Neural_Net.rmsprop(x_train, y_train, x_val, y_val)
    elif optimizer == 'adam':
      Neural_Net.adam(x_train, y_train, x_val, y_val)
    elif optimizer == 'nadam':
      Neural_Net.nadam(x_train, y_train, x_val, y_val)
    return 0



def train_NN(config):
  eph = config['epochs']
  num_hidden_layers = config['num_hidden_layers']
  hidden_layer_size = config['hidden_layer_size']
  weight_decay = ['weight_decay']
  learning_rate = config['learning_rate']
  optimizer = config['optimizer']
  batchsize = config['batch_size']
  weight_initialization = config['weight_initialization']
  activation_function = config['activation_function']


  l_size =[]
  l_size.append(x_train.shape[1])
  for i in range(num_hidden_layers):
    l_size.append(hidden_layer_size)
  l_size.append(10)
  Neural_Net = FFNN(layer_sizes=l_size,L = num_hidden_layers, epochs=eph, l_rate=learning_rate, batch_size=batchsize, activation_func=activation_function, loss_func='squared_error', output_activ_func='softmax', initializer=weight_initialization)
  train(x_train, y_train_onehot, x_test, y_test_onehot, optimizer,Neural_Net)
  test_acc, test_loss, _, _ = Neural_Net.model_performance(x_test, y_test_onehot)
  wandb.log({"val_accuracy": test_acc, "val_loss":test_loss})

def main():
    '''
    WandB calls main function with random combination,

    We log the values obtain from the given hypermeters.

    '''


    with wandb.init() as run:

        run_name="-ac_"+wandb.config.activation_function+"-hs"+str(wandb.config.hidden_layer_size)
        wandb.run.name=run_name
        train_NN(wandb.config)


wandb.agent(sweep_id, function=main, count = 10) # calls main function for count number of times.
wandb.finish()

wandb.finish()

